import InputWrapper from '@/templates/input';

export const userInfoInputsObj = {
  emailInput: new InputWrapper({
    classNameInput: 'userinfo',
    className: 'email',
    labelFor: 'email',
    inputType: 'email',
    labelText: 'Email',
    placeholder: 'Введите почту',
    required: true,
    validationPattern: new RegExp(
      /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
    ),
    validationErrorText: 'Не валидная почта',
  }),
  loginInput: new InputWrapper({
    classNameInput: 'userinfo',
    className: 'login',
    labelFor: 'login',
    inputType: 'text',
    labelText: 'Логин',
    placeholder: 'Введите логин',
    required: true,
    validationPattern: new RegExp(
      /^(?=.*[a-zA-Z])(?!^\d+$)[a-zA-Z0-9-_]{3,20}$/,
    ),
    validationErrorText:
      'Логин должен содержать от 3 до 20 символов, латиница, может содержать цифры, но не состоять из них, без пробелов, без спецсимволов (допустимы дефис и нижнее подчёркивание)',
  }),
  firstNameInput: new InputWrapper({
    classNameInput: 'userinfo',
    className: 'firstName',
    labelFor: 'firstName',
    inputType: 'text',
    labelText: 'Имя',
    placeholder: 'Введите имя',
    required: true,
    validationPattern: new RegExp(/^[A-ZА-ЯЁa-zа-яё]+(?:-[A-ZА-ЯЁa-zа-яё]+)*$/),
    validationErrorText: 'Имя содержит недопустимый символ',
  }),
  secondNameInput: new InputWrapper({
    classNameInput: 'userinfo',
    className: 'secondName',
    labelFor: 'secondName',
    inputType: 'text',
    labelText: 'Фамилия',
    placeholder: 'Введите фамилию',
    required: true,
    validationPattern: new RegExp(/^[A-ZА-ЯЁa-zа-яё]+(?:-[A-ZА-ЯЁa-zа-яё]+)*$/),
    validationErrorText: 'Фамилия содержит недопустимый символ',
  }),
  nicknameInput: new InputWrapper({
    classNameInput: 'userinfo',
    className: 'usernickname',
    labelFor: 'username',
    inputType: 'text',
    labelText: 'Имя в чате',
    placeholder: 'Введите имя в чате',
    required: true,
    validationPattern: new RegExp(/^[A-ZА-ЯЁa-zа-яё]+(?:-[A-ZА-ЯЁa-zа-яё]+)*$/),
    validationErrorText: 'Имя в чате содержит недопустимый символ',
  }),
  phoneInput: new InputWrapper({
    classNameInput: 'userinfo',
    className: 'phone',
    labelFor: 'phone',
    inputType: 'tel',
    labelText: 'Телефон',
    placeholder: 'Введите телефон',
    required: true,
    validationPattern: new RegExp(/^\+?\d{10,15}$/),
    validationErrorText: 'Не валидный номер',
  }),
};
