export const userInfoInputsObj = () => ({
  emailInput: {
    classNameInput: 'userinfo',
    className: 'email',
    labelFor: 'email',
    inputType: 'email',
    labelText: 'Email',
    placeholder: 'Введите почту',
    required: true,
    validationPattern: new RegExp(
      /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
    ),
    validationErrorText: 'Не валидная почта',
    value: window.userInfo?.email,
  },
  loginInput: {
    classNameInput: 'userinfo',
    className: 'login',
    labelFor: 'login',
    inputType: 'text',
    labelText: 'Логин',
    placeholder: 'Введите логин',
    required: true,
    validationPattern: new RegExp(
      /^(?=.*[a-zA-Z])(?!^\d+$)[a-zA-Z0-9-_]{3,20}$/,
    ),
    validationErrorText:
      'Логин должен содержать от 3 до 20 символов, латиница, может содержать цифры, но не состоять из них, без пробелов, без спецсимволов (допустимы дефис и нижнее подчёркивание)',
    value: window.userInfo?.login,
  },
  firstNameInput: {
    classNameInput: 'userinfo',
    className: 'firstName',
    labelFor: 'first_name',
    inputType: 'text',
    labelText: 'Имя',
    placeholder: 'Введите имя',
    required: true,
    validationPattern: new RegExp(/^[A-ZА-ЯЁa-zа-яё]+(?:-[A-ZА-ЯЁa-zа-яё]+)*$/),
    validationErrorText: 'Имя содержит недопустимый символ',
    value: window.userInfo?.first_name,
  },
  secondNameInput: {
    classNameInput: 'userinfo',
    className: 'secondName',
    labelFor: 'second_name',
    inputType: 'text',
    labelText: 'Фамилия',
    placeholder: 'Введите фамилию',
    required: true,
    validationPattern: new RegExp(/^[A-ZА-ЯЁa-zа-яё]+(?:-[A-ZА-ЯЁa-zа-яё]+)*$/),
    validationErrorText: 'Фамилия содержит недопустимый символ',
    value: window.userInfo?.second_name,
  },
  nicknameInput: {
    classNameInput: 'userinfo',
    className: 'usernickname',
    labelFor: 'display_name',
    inputType: 'text',
    labelText: 'Имя в чате',
    placeholder: 'Введите имя в чате',
    required: true,
    validationPattern: new RegExp(/^[A-ZА-ЯЁa-zа-яё]+(?:-[A-ZА-ЯЁa-zа-яё]+)*$/),
    validationErrorText: 'Имя в чате содержит недопустимый символ',
    value: window.userInfo?.display_name,
  },
  phoneInput: {
    classNameInput: 'userinfo',
    className: 'phone',
    labelFor: 'phone',
    inputType: 'tel',
    labelText: 'Телефон',
    placeholder: 'Введите телефон',
    required: true,
    validationPattern: new RegExp(/^\+?\d{10,15}$/),
    validationErrorText: 'Не валидный номер',
    value: window.userInfo?.phone,
  },
});
